### ISSUE TITLE
900 KB JS file

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-frontend#15]
The website currently includes a whopping 900 KB JS file. Could we reduce this to something reasonable, like 150-300 KB?

**Comment by madnificent** [comment]
Could we enable server-side compression?  We do this in https://github.com/mu-semtech/ember-proxy-service with good results.

**Comment by dokterbob** [comment]
It's 1.16MB now, but 237.86 KB gzipped, which is roughly acceptable (but still impressive!)
