### ISSUE TITLE
Use search result for discovering file type, rather than search query

### ISSUE THREAD

**Issue by madnificent** [ipfs-search/ipfs-search-frontend#19]
The API has been extended (a while ago) allowing us to discover the file type without fetching the type or relying on the information from the search.  Discovering the file type makes the previews work more often and would make the overview nicer.

The filetype is currently supplied to the hint card.  We can remove it, calculate it where needed, cleaning up the code in one go.

**Comment by dokterbob** [comment]
Why not using the search query data, which now returns the type for all records? Or is that what you meant?

**Comment by madnificent** [comment]
Users aren't required to specify the type of the search.  We currently show a generic type if that is the case.  These types of searches don't receive a preview yet.  Though that seems like a nice feature to have.

**Comment by dokterbob** [comment]
Ah, I was wondering how you made the previews work. I totally get what you mean now. 

I thought you were hinting at the metadata API.

It would be great to have previews work everywhere, based on the mime type in the search results!

**Comment by dokterbob** [comment]
There is a `type` field on the search results now, as well as a `mimetype`.
