### ISSUE TITLE
Discussion: disable package-lock.json

### ISSUE THREAD

**Issue by madnificent** [ipfs-search/ipfs-search-frontend#20]
NPM has a package-lock.json to indicate specific dependencies which tends to be rather large.  Assuming dependencies use semantic versioning themselves, the lockfile provides little value.

There is value to be gotten from this lockfile when dependencies change incorrectly.  The value of this safety-net may be negated by the change of file format across NPM versions.  We have disabled the use of this lockfile globally and across all of our projects for now.

Should we disable the package-lock.json explicitly for this repository so people that clone it don't encounter the file and accidentally end up with a bunch of changes?

**Comment by dokterbob** [comment]
I am deploying directly from GIT using NPM on the server. I would like to keep doing this, in which case a reproducible build is a must.

I just think, on the long run, we don't want 6k in dependencies!

**Comment by madnificent** [comment]
I'm sorry, but this is a known problem in JavaScript dependencies.  They're all pulled in as build-time dependencies.  Many of them run in order to build the contents (babel, being a nice example).  I doubt we'll solve the JS ecosystem's issues in the short run, but I'm sure relevant people will work on it.

So, do we disable the package-lock.json for now?

**Comment by dokterbob** [comment]
Only if we find a way to have **reproducible builds** with only npm available.

**Comment by madnificent** [comment]
Fully agree on the build process.  The package-lock.json files have caused us issues.  They are premature until we have a solid build (eg using Docker) for this repository with a fixed NPM version and until we can ensure the current devs have sufficiently similar NPM versions with respect to the package-lock files.

In this light, given that the specific NPM version likely matters, I'm removing the package-lock.json and I'm creating a story for a clean Docker build using our standard tooling.  The package-lock topic should be revisited in somewhat under a year from now.

**Comment by dokterbob** [comment]
May I suggest explicitly specifying the NPM version and other dependencies required and creating Travis builds? 

As we are deploying straight from GitHub to the server, Docker is a requirement I would not be too happy with - as I want to automate the build system and Docker (currently) isn’t suitable for deployment.

Thanks!

**Comment by madnificent** [comment]
I'd strongly prefer not to be bothered at this time to be honest.  We have a known build system that has worked for a long time and has not let us down. I have no experience in figuring out the right NPM versions and how to cope with incorrect versions.  I have had no need to do so in the past.  We have no issues with Docker in deployment.

We automate the build system using Docker.  Would you mind getting the built files from within a Docker image?

**Comment by dokterbob** [comment]
If you tell me how to run builds with Docker and then where and how to get the files out, for now, that would suffice.

But in the long run I’d strongly prefer not to make Docker a hard requirement (for various reasons).
