### ISSUE TITLE
Reproducible builds using Docker

### ISSUE THREAD

**Issue by madnificent** [ipfs-search/ipfs-search-frontend#23]
Set up a reproducible build for an NGINX server that hosts the ember app.  The common structure of https://github.com/mu-semtech/ember-proxy-service can be followed.

**Comment by dokterbob** [comment]
Note that Docker is not suitable for us in production, especially not if we can make static builds of the Ember app. Note #20.

Ideally, we'd need an automated way to create an archive on every push, as it seems hard to perform reproducible builds of Ember apps on the client side. These archives could then be directly deployed in production. Note that Travis would suit this purpose.

**Comment by dokterbob** [comment]
Note that I would be totally okay with a (neat, readable) Docker build for dev builds - that's actually the strategy I'm implementing across our entire infrastructure.

**Comment by madnificent** [comment]
Sorry.  I strongly disagree.  Feel free to figure out something else.

**Comment by dokterbob** [comment]
My strong suggestion would be to have an Ember app which can be build and deployed using the official Ember documentation, particularly to allow others to engage in the project.

I do not mind using Docker on top of that, to create a more uniform/reproducible build environment that is quick to get started with.
