### ISSUE TITLE
Keep filename in URL

### ISSUE THREAD

**Issue by hazae41** [ipfs-search/ipfs-search-frontend#24]
As described here: https://github.com/ipfs/go-ipfs/blob/master/docs/gateway.md#filenames

All direct URLs should have an extra parameter `filename` with the file name in order to let the browser find the file type and display the content correctly

Example:
`https://ipfs.io/ipfs/<hash>?filename=<filename>.<extension>`
Or even with extension only
`https://ipfs.io/ipfs/<hash>?filename=.<extension>`

This seems easy to implement because we always have the filename or the mime type provided by the metadata

**Comment by dokterbob** [comment]
@madnificent Any chance we might implement this some time soon?

**Comment by madnificent** [comment]
@dokterbob Can you remind me where I find the filename and/or the extension when they exist?

**Comment by dokterbob** [comment]
Good point. They’re currently in the references property which is not (yet) returned by the API. I’m cool with extending the API that way.

https://github.com/ipfs-search/ipfs-search-api <https://github.com/ipfs-search/ipfs-search-api>
