### ISSUE TITLE
Directory filter not working

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-frontend#29]
https://ipfs-search.com/#/search?kind=directory&search=test doesn't actually filter by directory.

Example output should be: https://api.ipfs-search.com/v1/search?q=test%20_type:directory

**Comment by dokterbob** [comment]
@madnificent It would be really great if you could lend a hand with this one.

**Comment by madnificent** [comment]
This is strange.  Has the API changed?  Implementation with a separate property seemed cleaner to me.

I will look into the issue regardless and will push to a feature branch.  If we could use query params for separate pieces of information, that would feel cleaner to me.

**Comment by dokterbob** [comment]
The API hasn't changed. Queries go straight to elasticsearch, essentially. Next version of the API may see a cleaner implementation.

**Comment by madnificent** [comment]
Oops.  Thanks for pointing me to it.
