### ISSUE TITLE
New release :)

### ISSUE THREAD

**Issue by madnificent** [ipfs-search/ipfs-search-frontend#37]
@vandrongelen @dokterbob An issue for keeping up with drafting the next release as mentioned in #36.  Helps us keep it separate from specific issues.  Feel free to comment or add to this issue ^_^

- [ ] Merge changes of #36
- [ ] Approve or clean #7 #32
- [ ] Ship it!

**Comment by dokterbob** [comment]
Perhaps it's better to use milestones for this https://github.com/ipfs-search/ipfs-search-frontend/milestones

**Comment by madnificent** [comment]
I've created a milestone.  It seems milestones don't show up in magit-forge partially breaking my workflow.  Will see how this lands :)
