### ISSUE TITLE
Feature: Image/Video/etc. specialized search

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs-search/ipfs-search-frontend#44]
Might be a good idea to have these to make IPFS on par with most search engines.
Also would be good to have a separate search page to tailor to these file types.

**Comment by DonaldTsang** [comment]
@dokterbob this might sound like a tough order, but the Image/Video does not have previews (i.e. image thumbnails) like how Google does. Also for Audio/Video maybe file metadata can be used for search. Another issue is that the highlighted text in the search engine are very often "not useful" as Google's e.g. unrelated file hashes and IPFS JSON metadata.

**Comment by ivan386** [comment]
@dokterbob How about search image by image?

**Comment by DonaldTsang** [comment]
@ivan386 separate issue please

**Comment by dokterbob** [comment]
Yeah, thumbnails should be on the roadmap. Feel free to create an issue for this, as it’s a though one also in terms of backend implementation.

> Op 11 mei 2019, om 06:33 heeft Donald Tsang <notifications@github.com> het volgende geschreven:
> 
> @dokterbob <https://github.com/dokterbob> this might sound like a tough order, but the Image/Video does not have previews (i.e. image thumbnails) like how Google does. Also for Audio/Video maybe file metadata can be used for search.
> 
>
