### ISSUE TITLE
IPFS file links should use gateway.ipfs.io instead of ipfs.io

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-frontend#5]

**Comment by madnificent** [comment]
The links are currently generated in the templates.  The fastest way to solve this would be to search for all occurences of https://ipfs.io/ipfs and replacing them with https://gateway.ipfs.io inside of the templates.

Alternatively, a helper could be made to generate the correct link for a given hash or path.

**Comment by dokterbob** [comment]
I would prefer the latter as there is now a reliable way to detect if IPFS is running - and if it isn’t we would want to start a local JS IPFS node. So it would be nice to have a central place to do this.

**Comment by madnificent** [comment]
Detecting the local node is a different problem, I think.  One issue is to use the correct public gateway, another is to search for a local gateway if it exists.

The use of a helper makes for cleaner templates.  It might help us to use a different domain in the future (I guess), but I don't know how to detect it properly at the time of writing.

**Comment by dokterbob** [comment]
That’ll be a separate issue but having the infrastructure to change it would be great to have available.

**Comment by ivan386** [comment]
File links should start from "/ipfs/". If ipfs-search opened from some gateway it will use that gateway to show found content.

**Comment by dokterbob** [comment]
You mean that if the user is running ipfs, it should use /ipfs/ URL’s and otherwise a gateway?

1. This should be ipfs:// - this is the URL space that’s reserved for this in some browsers.
2. Users who will have IPFS runnning will usuall have IPFS Station running, which automatically redirects from the gateway to the local running node.

**Comment by ivan386** [comment]
Example: https://cloudflare-ipfs.com/ipfs/Qmf8pSQazshENpn8opE395z5bBWUoD43Gv1mQCASeSdqhW/
Now links to files starts from "https://ipfs.io" and go to ipfs.io.

If you remove that part("https://ipfs.io") than link will become relative and open on "https://cloudflare-ipfs.com" instead of "https://ipfs.io".

If user open search from local gateway "http://127.0.0.1:8080/ipfs/Qmf8pSQazshENpn8opE395z5bBWUoD43Gv1mQCASeSdqhW/" it will use local gateway to show content.

And you can do redirect from "https://ipfs-search.com/ipfs/<hash>" to "https://gateway.ipfs.io/ipfs/<hash>"

**Comment by dokterbob** [comment]
This would only work if we’re running a gateway and/or serving our site over IPFS.

Which we should, and we might, but we don’t - right now.

**Comment by ivan386** [comment]
> This would only work if we’re running a gateway and/or serving our site over IPFS.

Then what is it([/ipfs/Qmf8pSQazshENpn8opE395z5bBWUoD43Gv1mQCASeSdqhW/](https://cloudflare-ipfs.com/ipfs/Qmf8pSQazshENpn8opE395z5bBWUoD43Gv1mQCASeSdqhW/))

You can do simple redirect from "https://ipfs-search.com/ipfs/[hash]" to "https://gateway.ipfs.io/ipfs/[hash]".

**Comment by dokterbob** [comment]
What would be the advantage(s) in that?

**Comment by dokterbob** [comment]
Also, note that this would increase (rather than simplify) maintenance for us.

Obviously, this is definitely our goal in the longer term. But we’d want to do it well and use IPNS, which does give some complications. Hence, we are a bit careful with it.

**Comment by ivan386** [comment]
> What would be the advantage(s) in that?

If you use relative links content will be replicated on gateways that user use to open search page. And this decrease load on gateway.ipfs.io.

**Comment by dokterbob** [comment]
> If you use relative links content will be replicated on gateways that user use to open search page.
Good point. Do you think people are using many gateways other than CloudFlare and IPFS's one, at this point?

> And this decrease load on gateway.ipfs.io.
True.

Perhaps it would be desirable and feasible for us to run our own gateway on our frontend server. IPFS's resource usage has gone done so it might be. That would be a good moment to start hosting over IPFS - as well as implementing relative links.
