### ISSUE TITLE
Show parent directories

### ISSUE THREAD

**Issue by ivan386** [ipfs-search/ipfs-search-frontend#53]
When i search for file in ipfs-search i see that it have long path in the name.
Example:
```\distributed_lab\Новичок\extra\habr\SPHINCS — Википедия_files\444px-Binary_hash_tree.png```

 I want to browse folder that contain that file but have only file hash. Can you additional show directory hash in file properties? It can be hash of root directory (```\```) and directory that contains that file (```SPHINCS — Википедия_files```).

**Comment by dokterbob** [comment]
Yes, this would be a great feature. I've already prepared the API to give back `references` (`name` and `parent_hash`). This also allows us to link to files within a directory, causing websites to function etc.
