### ISSUE TITLE
Usability; its not evident that the rows can be clicked on

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-frontend#6]
In the list view, it is not evident to users that rows can be clicked on, it seems that only the hashes can be clicked - resulting in users clicking on hashes and often missing out on our very handsome preview functionality.

**Comment by madnificent** [comment]
@vandrongelen Does this fit within a larger challenge of supporting https://webaim.org/techniques/keyboard/ or is it mainly the hand icon we can add in CSS?

**Comment by dokterbob** [comment]
Seems solved in master.
