### ISSUE TITLE
When i open this page it infinity loading more and more same results

### ISSUE THREAD

**Issue by ivan386** [ipfs-search/ipfs-search-frontend#60]
When i open this page it infinity loading more and more same results

https://ipfs-search.com/#/search?page=21&search=%22%D0%A5%D0%B0%D0%B1%D1%80%22

**Comment by dokterbob** [comment]
Wow. That's an intricate one! Great find!

We're currently not maintaining the old frontend because we are approaching release of the new one. The new one is in VueJS and any contributions are greatly appreciated!

**Comment by dokterbob** [comment]
https://github.com/ipfs-search/dweb-search-frontend
