### ISSUE TITLE
Show metadata in preview view

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-frontend#7]
At least having a link to formatted metadata would be nice, or having some or all fields available there would be really cool.

See: https://api.ipfs-search.com/#metadata

**Comment by madnificent** [comment]
@docterbob Could you check the operation and documentation of the metadata api again? It seems I can't make calls to it.  Perhaps I'm missing a header or something like that?

**Comment by dokterbob** [comment]
Seems an issue related to the recent server migration. Created a ticket for it, will look at it when SSH is not firewalled. ;)

**Comment by dokterbob** [comment]
Issue fixed ready to go!

**Comment by madnificent** [comment]
Resolved by #32 and #39
